### ISSUE TITLE
MobX 7 roadmap

### ISSUE THREAD

**Issue by mweststrate** [mobxjs/mobx#3796]
[WIP for now, needed the issue number]

* [ ] Remove legacy decorators support
* [ ] Remove deprecated APIs
   * [ ] ...
* [ ] Remove mobx-react / observer class support?
* [ ] Remove Provider/inject
* [ ] Remove deprecated mobx-react-lite hooks
* [ ] ESM support
* [ ] ....
* [ ] Remove trace
* [ ] Remove intercept / observer
* [ ] Remove legacy array support (non-proxied)
* [ ] Remove some configuration options?
* [ ] Modern build / test system
* [ ] Remove v4 unit tests

**Comment by pzmosquito** [comment]
awesome news! It looks like the new version will be focused on removing deprecated stuff and updating the build system instead of introducing new features or breaking changes. It should be a breeze to upgrade!

**Comment by kubk** [comment]
I have a somewhat controversial suggestion: automatically bind class methods in `makeAutoObservable`/`makeObservable`. The idea is to set `{ autoBind: true }` as the default, while still offering the option to disable it with `{ autoBind: false }`.

Rationale: People might forget to bind `this`. Here are a few examples:
- https://github.com/mobxjs/mobx/discussions/3795#discussioncomment-7567426
- https://github.com/mobxjs/mobx/discussions/2496#discussioncomment-92094

Developers these days don't usually deal with `this`, `.call`, or `.apply`, as was common before. Hence, the cause of the issue isn't immediately clear to them. They may experience loss of reactivity and attribute it to Mobx. While there might be reasons to preserve the original `this` by default, I fail to see them. All of my Mobx stores use `{ autoBind: true }`. Also, though I'm not a Vue expert, it seems they bind `this` as well: [Vue.js Computed Properties](https://v2.vuejs.org/v2/guide/computed.html).

```javascript
  computed: {
    // a computed getter
    reversedMessage: function () {
      // `this` points to the vm instance
      return this.message.split('').reverse().join('')
    }
  }
  
Perhaps we could even consider making new `@action` / `@flow` decorators bound by default, as well as introducing `@action.unbound` / `@flow.unbound`. I can work in this PR.

**Comment by kiejo** [comment]
As a long-time user of MobX I would be in favor of keeping support for mobx-react / observer classes as it's still fully supported by React. I understand why new code bases might not use class based components, but for existing code bases it doesn't necessarily make sense to migrate all existing code if it still works well.

**Comment by mweststrate** [comment]
> I have a somewhat controversial suggestion: automatically bind class methods in makeAutoObservable/makeObservable. The idea is to set { autoBind: true } as the default, while still offering the option to disable it with { autoBind: false }.
> Rationale: People might forget to bind this. Here are a few examples:

Interesting! The rationale for not doing so was that autobinding is expensive; it creates a function closure per instance rather than per type. MST does autobinding and I regretted that, due to the mem / cpu consumption. So I'm a bit torn on this one, being able to opt out can avoid the MST problem. On the other hand, if `@action` doesn't bind, while `makeObservable` does, that might be confusing. Maybe just `makeAutoObservable`, which is than an alias for "the most inefficient but convenient way to make observables"?

**Comment by mweststrate** [comment]
> As a long-time user of MobX I would be in favor of keeping support for mobx-react / observer classes as it's still fully supported by React. I understand why new code bases might not use class based components, but for existing code bases it doesn't necessarily make sense to migrate all existing code if it still works well.

Without provider / inject, and non-reactive props/state like in the latest version, `mobx-react` `observer` has actually become a really thin wrapper around mobx-react-lite's `observer`, so it might be worth just merging them again.

**Comment by kiejo** [comment]
> Without provider / inject, and non-reactive props/state like in the latest version, mobx-react observer has actually become a really thin wrapper around mobx-react-lite's observer, so it might be worth just merging them again.

That sounds great!

**Comment by vincentLiuxiang** [comment]
> Remove mobx-react / observer class support?

Hi @mweststrate can we keep observer for class?

Even though functional/hooks React components are very popular in nowdays, Oop programming is still very highly efficient for some UI interaction complex scenarios.

Eg: 

When 2 pages are 90% similar, we can finish Page A. Page B can extend Page A and share 90% of the code, only overriding 10%.

The code between PageA and PageB is completely isolated and not coupled. so the code is very clean, which is conducive to later maintenance.

```ts
@observer 
class PageA extends React.component {
  renderSharedSection() {...}
  renderDiffSection() {...}
  render() {
     return (
       <>
         {this.renderSharedSection()}
         {this.renderDiffSection()}
       </>
     );
  }
}

class PageB extends PageA {
   renderDiffSection() {...}
}
```

Currently, we are in charge of more than 20+ products, web-IDE, data visualization etc...
This feature really helps us to improve our code quality and dev efficiency.

hope you can keep observer for class in the V7 version

(Since v6 doesn't support @ decorator, we are very excited to know V7 is coming 😂)

**Comment by mweststrate** [comment]
@vincentLiuxiang  see also the comments just before yours :). P.s. v6 does support `@` decorator now: https://michel.codes/blogs/mobx-decorators

**Comment by vincentLiuxiang** [comment]
> @vincentLiuxiang see also the comments just before yours :). Rephrased in the proposal. P.s. v6 does support `@` decorator now: https://michel.codes/blogs/mobx-decorators
 
👍👍👍
@mweststrate 

would like to confirm whether there is any API incompatibility when upgrading from 6.10.0 to 6.11.0 ?

**Comment by mweststrate** [comment]
not by design (unless you switch from legacy to modern decorators)

**Comment by terrasoff** [comment]
Considering the massive feature removal, sounds like the bundle size will be significantly reduced :+1:

**Comment by emereum** [comment]
Can there be a clear upgrade path for large codebases? For example if there are breaking changes can codemods be provided? Or alternatively, can the breaking changes be made in such a way that consumers could write their own codemods?

If you'd like feedback on what breaks / what works in large codebases at certain points through this roadmap I would be happy to contribute.

**Comment by Bnaya** [comment]
It's worth pinning this issue <3

**Comment by PeterPCardenas** [comment]
@mweststrate You're referring to intercept and observe [here](https://mobx.js.org/intercept-and-observe.html#observe), not the observer HOC correct?

**Comment by xaviergonz** [comment]
is there an alternative to intercept and observe? mobx-keystone relies on those heavilty

**Comment by MirKml** [comment]
> I have a somewhat controversial suggestion: automatically bind class methods in `makeAutoObservable`/`makeObservable`. The idea is to set `{ autoBind: true }` as the default, while still offering the option to disable it with `{ autoBind: false }`.
> 
> Interesting! The rationale for not doing so was that autobinding is expensive; it creates a function closure per instance rather than per type. MST does autobinding and I regretted that, due to the mem / cpu consumption. So I'm a bit torn on this one, being able to opt out can avoid the MST problem. On the other hand, if `@action` doesn't bind, while `makeObservable` does, that might be confusing. Maybe just `makeAutoObservable`, which is than an alias for "the most inefficient but convenient way to make observables"?

I'm against default { autobind: true }, we had many stores `makeAutoObservable` with autobind : true, but we removed them all. Reason - when we applied eslint, we realized that autobinded methods are unwanted magic.

store class
```
export class Store {
    constructor() {
        makeAutoObservable(this, null, { autoBind: true });
    }
    
    setSelectedOption(selectedOption) {
        this.selectedOption = selectedOption;
        this.consumerOnChange?.(this.selectedOption?.value);
    }
}
```
eslint knows nothing about magic autobind for setSelectedOption and complains in every such method usage as event handlers.

![image](https://github.com/mobxjs/mobx/assets/21239658/d1241437-73f8-441d-a448-f8c0bdd85d64) 

We fixed this with proper use of arrow function instead of plain method
```
    setSelectedOption = (selectedOption) => {
        this.selectedOption = selectedOption;
        this.consumerOnChange?.(this.selectedOption?.value);
    }
```
As result we have clear readable validated code with correct binding without any autobind magic.
We clear tons such autobinds and makes our event handler as arrow functions.

Plese don't add autobind as default (@kubk @mweststrate).

**Comment by zhangchao828** [comment]
Has there been any progress？

**Comment by kubk** [comment]
For anyone interested in following, here's the PR for the upcoming major version of Mobx: https://github.com/mobxjs/mobx/pull/4671
